source 'http://rubygems.org'

gem 'rails', '3.0.1'
gem 'faker', '0.3.1'
gem 'will_paginate', '3.0.pre2'
gem 'authlogic', '2.1.6'
gem 'meta_search', '0.9.8'
gem 'mysql', '2.8.1'
gem 'nokogiri', '1.4.3.1'
gem 'jquery-rails', '0.2.5'
gem 'jpmobile', '0.1.3'
gem 'jpmobile-ipaddresses', '0.0.1'
gem 'jpmobile-terminfo', '0.0.2'
gem 'ruby-mysql', '2.9.3'
gem 'paperclip', '2.3.6'
gem 'lazy_high_charts'
gem 'delayed_job'
gem 'i18n_generators'
gem 'validates_timeliness'
gem 'sunspot_rails', '1.2.1'

