development:
  adapter: mysql
  database: coupon_star
  username: root
  password: admin
  host: 127.0.0.1
  encoding: utf8

test:
  adapter: mysql
  database: coupon_star
  username: root
  password: admin
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: mysql
  database: coupon_star
  username: root
  password: admin
  host: 127.0.0.1
  encoding: utf8

